apiVersion: v1
kind: Service
metadata:
  name: jenkins-web-ui
  namespace: cicd
  labels:
    app: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30003
      name: web-ui
    - port: 50000
      targetPort: 50000
      name: agent
  selector:
    app: jenkins
    tier: jenkins
#---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: jenkins-web-ui
#  namespace: cicd
#spec:
#  rules:
#  - host: jenkin.intel.com
#    http:
#      paths:
#      - backend:
#          serviceName: jenkins-web-ui
#          servicePort: 8023
