apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: jenkins
  name: jenkins-admin-sa
  namespace: cicd

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: jenkins-admin-sa
subjects:
  - kind: ServiceAccount
    name: jenkins-admin-sa
    namespace: cicd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin 
